/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controlador_CRUD;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.Categoria;
import model.Vaixell;

/**
 *
 * @author marc
 */
public class gui_formulari extends javax.swing.JDialog {

    /**
     * Creates new form gui_formulari
     */
    Controlador_CRUD ctl;
    Vaixell v = null;

    public gui_formulari(java.awt.Frame parent, Controlador_CRUD ctl, Vaixell v) throws SQLException {

        super(parent, true);
        this.v = v;
        this.ctl = ctl;
        initComponents();
        for (int i = 1; i <= 3; i++) {
            this.jComboBox1.addItem(ctl.carregaCategoria(i));
        }
        if (this.v != null) {
            plenaTaula();
            this.jbAfegir.setText("Actualitza");

            this.jtCodi.setEnabled(false);
        }
    }

    public void plenaTaula() {

        this.jtCodi.setText(String.valueOf(v.getCodi()));
        this.jtNom.setText(v.getNom());

        this.jComboBox1.setSelectedIndex(v.getCategoria().getCodi() - 1);

        this.jtRating.setText(String.valueOf(v.getRating()));
        this.jtClub.setText(v.getClub());

        if (this.jRadioButton1.getText().equals(v.getTipusVaixell())) {
            this.jRadioButton1.setSelected(true);
        } else if (this.jRadioButton2.getText().equals(v.getTipusVaixell())) {
            this.jRadioButton2.setSelected(true);
        } else {
            this.jRadioButton3.setSelected(true);
        }
        if (v.isSenior()) {
            this.cbSenior.setSelected(true);
        } else {
            this.cbSenior.setSelected(false);
        }
        this.jtTemps.setText(String.valueOf(v.getTempsReal()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jtTemps = new javax.swing.JTextField();
        jtRating = new javax.swing.JTextField();
        jtClub = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbAfegir = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jtCodi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtNom = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbSenior = new javax.swing.JCheckBox();
        jlECodi = new javax.swing.JLabel();
        jlENom = new javax.swing.JLabel();
        jlERating = new javax.swing.JLabel();
        jlEClub = new javax.swing.JLabel();
        jlETemps = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        jtTemps.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtTempsKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtTempsKeyReleased(evt);
            }
        });

        jtRating.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtRatingKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtRatingKeyReleased(evt);
            }
        });

        jtClub.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtClubFocusLost(evt);
            }
        });
        jtClub.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtClubKeyReleased(evt);
            }
        });

        jLabel2.setText("Nom");

        jLabel3.setText("Categoria");

        jLabel4.setText("Rating");

        jLabel5.setText("Club");

        jbAfegir.setText("Afegir");
        jbAfegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAfegirActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("regata");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("creuer");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("creuer-regata");

        jLabel1.setText("Codi");

        jtCodi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtCodiFocusLost(evt);
            }
        });
        jtCodi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtCodiKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtCodiKeyReleased(evt);
            }
        });

        jLabel6.setText("Temps");

        jtNom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNomFocusLost(evt);
            }
        });
        jtNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNomActionPerformed(evt);
            }
        });
        jtNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtNomKeyReleased(evt);
            }
        });

        jLabel7.setText("Tipus Vaixell");

        jLabel8.setText("Senior");

        cbSenior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSeniorActionPerformed(evt);
            }
        });

        jlECodi.setBackground(new java.awt.Color(204, 0, 51));
        jlECodi.setForeground(new java.awt.Color(204, 0, 0));

        jlENom.setBackground(new java.awt.Color(204, 0, 0));
        jlENom.setForeground(new java.awt.Color(204, 0, 0));

        jlERating.setBackground(new java.awt.Color(204, 0, 0));
        jlERating.setForeground(new java.awt.Color(204, 0, 0));

        jlEClub.setBackground(new java.awt.Color(204, 0, 0));
        jlEClub.setForeground(new java.awt.Color(204, 0, 0));

        jlETemps.setBackground(new java.awt.Color(204, 0, 0));
        jlETemps.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtTemps, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbSenior)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButton1)
                                                .addGap(18, 18, 18)
                                                .addComponent(jRadioButton2))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel3)
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtClub)
                                    .addComponent(jtRating, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, 152, Short.MAX_VALUE)
                                    .addComponent(jtNom, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtCodi, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlEClub, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlECodi, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                    .addComponent(jlENom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlERating, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlETemps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jRadioButton3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jbAfegir)))
                .addGap(94, 96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtCodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlECodi, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jlENom, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlERating, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtClub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jlEClub, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3))
                        .addGap(74, 74, 74)
                        .addComponent(jLabel8))
                    .addComponent(cbSenior, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtTemps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlETemps, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jbAfegir)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private Vaixell creaVaixell() {
        try {
            int codi = Integer.parseInt(this.jtCodi.getText());
            String nom = this.jtNom.getText();
            Categoria cat = new Categoria();
            cat.setCodi(this.jComboBox1.getSelectedIndex());
            cat.setNom(this.jComboBox1.getItemAt(this.jComboBox1.getSelectedIndex()));
            double rating = Double.parseDouble(this.jtRating.getText());
            String club = this.jtClub.getText();
            String tipusVaixell;

            if (this.jRadioButton1.isSelected()) {
                tipusVaixell = this.jRadioButton1.getText();
            } else if (this.jRadioButton2.isSelected()) {
                tipusVaixell = this.jRadioButton2.getText();
            } else {
                tipusVaixell = this.jRadioButton3.getText();
            }
            boolean senior = this.cbSenior.isSelected();
            double tempsReal = Double.parseDouble(this.jtTemps.getText());

            Vaixell va = new Vaixell(codi, nom, cat, rating, club, tipusVaixell, senior, tempsReal);
            return va;
        } catch (Exception e) {
            return null;
        }
    }
    private void jbAfegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAfegirActionPerformed
        // TODO add your handling code here

        Vaixell va = this.creaVaixell();
        try {

            if (this.v == null) {
                va.getCategoria().setCodi(va.getCategoria().getCodi() + 1);
                ctl.afegirVaixell(va);
                JOptionPane.showMessageDialog(this, "Vaixell afegit correctament");
            } else {

                ctl.updateVaixell(va);
                JOptionPane.showMessageDialog(this, "Vaixell modificat correctament");
            }

        } catch (SQLException ex) {
            //  Logger.getLogger(gui_formulari.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error");
        } finally {
            this.dispose();
        }
    }//GEN-LAST:event_jbAfegirActionPerformed

    private void cbSeniorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSeniorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSeniorActionPerformed

    private void jtNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNomActionPerformed

    private void jtCodiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCodiFocusLost
        // TODO add your handling code here:
        this.jtCodi.setEditable(true);
        boolean isOk = ctl.validaVacio(this.jtCodi.getText());
        if (!isOk) {
            this.jlECodi.setText("No es permet camp vuit");
        } else {
            if (this.v == null) {

                try {

                    boolean ena = ctl.validaCodi(Integer.parseInt(this.jtCodi.getText()));
                    // this.jbAfegir.setEnabled(ena);
                    if (!ena) {
                        this.jlECodi.setText("Codi Erroni");
                    } else {
                        this.jlECodi.setText("");
                    }
                } catch (Exception ex) {
                    //     Logger.getLogger(gui_formulari.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    }//GEN-LAST:event_jtCodiFocusLost

    private void jtCodiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCodiKeyPressed
        // TODO add your handling code here:
        char codi = evt.getKeyChar();

        //   System.out.println(Character.hashCode(codi));
        if (Character.isDigit(codi) || Character.hashCode(codi) == 8) {
            this.jtCodi.setEditable(true);
            this.jlECodi.setText("");
        } else {
            this.jtCodi.setEditable(false);
            this.jlECodi.setText("Solo se aceptan digitos");
        }
    }//GEN-LAST:event_jtCodiKeyPressed

    private void jtCodiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCodiKeyReleased
        // TODO add your handling code here:

        if (this.v == null) {

            try {

                boolean ena = ctl.validaCodi(Integer.parseInt(this.jtCodi.getText()));
                // this.jbAfegir.setEnabled(ena);
                if (!ena) {
                    this.jlECodi.setText("Codi Erroni");
                } else {
                    this.jlECodi.setText("");
                }
            } catch (Exception ex) {
                //     Logger.getLogger(gui_formulari.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jtCodiKeyReleased

    private void jtNomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomKeyReleased
        // TODO add your handling code here:
        boolean isOk = ctl.validaLength(this.jtNom.getText());
        if (!isOk) {
            this.jlENom.setText("Minim 3 lletres");
        } else {
            this.jlENom.setText("");
        }
    }//GEN-LAST:event_jtNomKeyReleased

    private void jtRatingKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtRatingKeyReleased
        // TODO add your handling code here:
        this.jtRating.setEditable(true);
    }//GEN-LAST:event_jtRatingKeyReleased

    private void jtClubKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtClubKeyReleased
        // TODO add your handling code here:
        boolean isOk = ctl.validaLength(this.jtClub.getText());
        if (!isOk) {
            this.jlEClub.setText("Minim 3 lletres");
        } else {
            this.jlEClub.setText("");
        }
    }//GEN-LAST:event_jtClubKeyReleased

    private void jtTempsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTempsKeyReleased
        // TODO add your handling code here:
        this.jtTemps.setEditable(true);
    }//GEN-LAST:event_jtTempsKeyReleased

    private void jtNomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNomFocusLost
        // TODO add your handling code here:
        this.jtNom.setEditable(true);
        boolean isOk = ctl.validaVacio(this.jtNom.getText());
        if (!isOk) {
            this.jlENom.setText("No es permet camp vuit");
        } else {
            isOk = ctl.validaLength(this.jtNom.getText());
            if (!isOk) {
                this.jlENom.setText("Minim 3 lletres");
            } else {
                this.jlENom.setText("");
            }
        }
    }//GEN-LAST:event_jtNomFocusLost

    private void jtClubFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtClubFocusLost
        // TODO add your handling code here:
        boolean isOk = ctl.validaVacio(this.jtClub.getText());
        if (!isOk) {
            this.jlEClub.setText("No es permet camp vuit");
        } else {
            isOk = ctl.validaLength(this.jtClub.getText());
            if (!isOk) {
                this.jlEClub.setText("Minim 3 lletres");
            } else {
                this.jlEClub.setText("");
            }
        }
    }//GEN-LAST:event_jtClubFocusLost

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        try {
            Vaixell v = this.creaVaixell();
            if (this.v == null) {
                if (v == null) {
                    this.jbAfegir.setEnabled(false);
                } else {
                    this.jbAfegir.setEnabled(ctl.validaVaixell(v));
                }
            }

        } catch (SQLException ex) {
            //      Logger.getLogger(gui_formulari.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formMouseMoved

    private void jtRatingKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtRatingKeyPressed
        // TODO add your handling code here:
        char codi = evt.getKeyChar();

        //    System.out.println(Character.hashCode(codi));
        if (Character.isDigit(codi) || Character.hashCode(codi) == 8 || Character.hashCode(codi) == 46) {
            this.jtRating.setEditable(true);
            this.jlERating.setText("");
        } else {
            this.jtRating.setEditable(false);
            this.jlERating.setText("Solo se aceptan digitos");
        }
    }//GEN-LAST:event_jtRatingKeyPressed

    private void jtTempsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTempsKeyPressed
        // TODO add your handling code here:
        char codi = evt.getKeyChar();

        //     System.out.println(Character.hashCode(codi));
        if (Character.isDigit(codi) || Character.hashCode(codi) == 8 || Character.hashCode(codi) == 46) {
            this.jtTemps.setEditable(true);
            this.jlETemps.setText("");
        } else {
            this.jtTemps.setEditable(false);
            this.jlETemps.setText("Solo se aceptan digitos");
        }
    }//GEN-LAST:event_jtTempsKeyPressed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(gui_formulari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(gui_formulari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(gui_formulari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(gui_formulari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                gui_formulari dialog = new gui_formulari(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbSenior;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JButton jbAfegir;
    private javax.swing.JLabel jlEClub;
    private javax.swing.JLabel jlECodi;
    private javax.swing.JLabel jlENom;
    private javax.swing.JLabel jlERating;
    private javax.swing.JLabel jlETemps;
    private javax.swing.JTextField jtClub;
    private javax.swing.JTextField jtCodi;
    private javax.swing.JTextField jtNom;
    private javax.swing.JTextField jtRating;
    private javax.swing.JTextField jtTemps;
    // End of variables declaration//GEN-END:variables
}
